spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        format-sql: true

url:
  address: /address
  customer: /customer
config:
  security:
    secretKey: 655368566B5970337336763979244226452948404D635166546A576E5A713474
